version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-cvreview}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cvreviewpass}
      - POSTGRES_DB=${POSTGRES_DB:-cvreview_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cvreview}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER:-cvreview}:${POSTGRES_PASSWORD:-cvreviewpass}@postgres:5432/${POSTGRES_DB:-cvreview_db}
      - SECRET_KEY=${SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: