/** Clear Review — polished blue product interface, calm hierarchy, practical feedback. */
'use client';

import { ChangeEvent, DragEvent, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CheckCircleRounded, DeleteOutlineRounded, DescriptionOutlined, FileUploadOutlined, UploadFileRounded } from '@mui/icons-material';
import { Alert, Box, Button, Chip, CircularProgress, Paper, Stack, Typography } from '@mui/material';
import { apiClient } from '@/app/utils/api-client';

type UploadResponse = { id: number };
type UploadFormProps = { credits: number };
const acceptedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
const maxBytes = 5 * 1024 * 1024;

export default function UploadForm({ credits }: UploadFormProps) {
  const router = useRouter(); const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [dragActive, setDragActive] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const selectFile = (candidate?: File) => { if (!candidate) return; if (!acceptedTypes.includes(candidate.type)) { setError('Choose a PDF, DOC, DOCX, or TXT file.'); return; } if (candidate.size > maxBytes) { setError('This file is larger than 5 MB. Choose a smaller version.'); return; } setFile(candidate); setError(''); };
  const upload = async () => { if (!file) { setError('Choose a CV file before starting the review.'); return; } if (credits < 1) { setError('You need at least one credit before starting a review.'); return; } setSubmitting(true); setError(''); try { const result = await apiClient.upload<UploadResponse>('reviews/upload', file); router.push(`/reviews/${result.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'We could not upload that CV. Please try again.'); } finally { setSubmitting(false); } };
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragActive(false); selectFile(event.dataTransfer.files?.[0]); };
  return <Stack spacing={3}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={2}><Box><Typography color="primary.main" fontWeight={800}>NEW REVIEW</Typography><Typography variant="h2" sx={{ fontSize: { xs: '2.35rem', md: '3rem' }, mt: 0.5 }}>Upload a CV</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Use the version you want to improve next. Your review uses one credit.</Typography></Box><Chip label={`${credits} credit${credits === 1 ? '' : 's'} available`} color={credits > 0 ? 'primary' : 'default'} sx={{ alignSelf: { xs: 'flex-start', sm: 'center' }, fontWeight: 750 }} /></Stack>
  {error && <Alert severity="error">{error}</Alert>}
  {credits < 1 && <Alert severity="warning">You need a credit to start a review. <Button size="small" onClick={() => router.push('/credits')}>View credits</Button></Alert>}
  <Paper elevation={0} onDragOver={(event) => { event.preventDefault(); setDragActive(true); }} onDragLeave={() => setDragActive(false)} onDrop={onDrop} onClick={() => inputRef.current?.click()} sx={{ cursor: 'pointer', border: '2px dashed', borderColor: dragActive ? 'primary.main' : file ? '#8DB0FF' : 'divider', bgcolor: dragActive ? 'primary.light' : file ? '#F5F8FF' : '#FBFCFE', p: { xs: 3.5, sm: 6 }, textAlign: 'center', transition: 'background 180ms ease, border-color 180ms ease' }}><input ref={inputRef} type="file" accept=".pdf,.doc,.docx,.txt" onChange={(event: ChangeEvent<HTMLInputElement>) => selectFile(event.target.files?.[0])} hidden />{file ? <Stack spacing={1.3} alignItems="center"><Box sx={{ width: 48, height: 48, borderRadius: 3, display: 'grid', placeItems: 'center', bgcolor: 'primary.main', color: 'primary.contrastText' }}><DescriptionOutlined /></Box><Typography fontWeight={800}>{file.name}</Typography><Typography variant="body2" color="text.secondary">{(file.size / 1024 / 1024).toFixed(2)} MB · ready for review</Typography><Button variant="text" size="small" startIcon={<DeleteOutlineRounded />} onClick={(event) => { event.stopPropagation(); setFile(null); }}>Remove file</Button></Stack> : <Stack spacing={1.25} alignItems="center"><Box sx={{ width: 52, height: 52, borderRadius: 3, display: 'grid', placeItems: 'center', bgcolor: 'primary.light', color: 'primary.main' }}><FileUploadOutlined /></Box><Typography variant="h6">Drop your CV here</Typography><Typography color="text.secondary">or click to browse your files</Typography><Typography variant="caption" color="text.secondary">PDF, DOC, DOCX, or TXT · maximum 5 MB</Typography></Stack>}</Paper>
  <Stack direction={{ xs: 'column-reverse', sm: 'row' }} justifyContent="space-between" spacing={1.5}><Button variant="text" onClick={() => router.push('/dashboard')} disabled={submitting}>Back to workspace</Button><Button variant="contained" size="large" startIcon={submitting ? <CircularProgress size={18} color="inherit" /> : <UploadFileRounded />} disabled={!file || submitting || credits < 1} onClick={() => void upload()}>{submitting ? 'Starting review…' : 'Start review'}</Button></Stack>
  <Box sx={{ px: 2, py: 1.5, bgcolor: '#F5F8FF', borderRadius: 3 }}><Stack direction="row" spacing={1} alignItems="center"><CheckCircleRounded color="primary" fontSize="small" /><Typography variant="body2" color="text.secondary">For the clearest result, upload a text-based PDF rather than a scanned image.</Typography></Stack></Box>
  </Stack>;
}
