/** Clear Review — polished blue product interface, calm hierarchy, practical feedback. */
'use client';
import { FormEvent, Suspense, useEffect, useState } from 'react'; import Link from 'next/link'; import { useRouter, useSearchParams } from 'next/navigation'; import { Visibility, VisibilityOff } from '@mui/icons-material'; import { Alert, Box, Button, CircularProgress, IconButton, InputAdornment, Stack, TextField, Typography } from '@mui/material'; import AuthShell from '@/app/components/auth/AuthShell'; import { apiClient } from '@/app/utils/api-client'; import { useAuth } from '@/app/components/AuthProvider';
function LoginForm() { const router = useRouter(); const searchParams = useSearchParams(); const { isAuthenticated, isLoading, refreshSession } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const registered = searchParams.get('registered') === '1'; useEffect(() => { if (!isLoading && isAuthenticated) router.replace('/dashboard'); }, [isAuthenticated, isLoading, router]); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const cleanEmail = email.trim().toLowerCase(); if (!cleanEmail || !password) { setError('Enter both your email and password.'); return; } setError(''); setSubmitting(true); try { await apiClient.login(cleanEmail, password); await refreshSession(); const from = searchParams.get('from'); router.replace(from?.startsWith('/') ? from : '/dashboard'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'We could not sign you in. Please try again.'); } finally { setSubmitting(false); } };
return <AuthShell eyebrow="Welcome back" title="Sign in to your workspace" subtitle="Pick up where you left off and keep your CV feedback organised."><Stack component="form" spacing={2.25} onSubmit={submit} noValidate>{registered && <Alert severity="success">Your account is ready. Sign in to start your first review.</Alert>}{error && <Alert severity="error">{error}</Alert>}<TextField label="Email address" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" autoFocus required fullWidth /><TextField label="Password" type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required fullWidth InputProps={{ endAdornment: <InputAdornment position="end"><IconButton aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((value) => !value)} edge="end">{showPassword ? <VisibilityOff /> : <Visibility />}</IconButton></InputAdornment> }} /><Button type="submit" variant="contained" size="large" disabled={submitting}>{submitting ? 'Signing you in…' : 'Sign in'}</Button><Box sx={{ textAlign: 'center' }}><Typography variant="body2" color="text.secondary">New to CV Review? <Link href="/register" style={{ color: '#2454D7', fontWeight: 750 }}>Create an account</Link></Typography></Box></Stack></AuthShell>; }

export default function LoginPage() {
  return <Suspense fallback={<Box sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>}><LoginForm /></Suspense>;
}
